# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main # Deploy only when pushing to the main branch
  pull_request:
    branches:
      - main # Run tests on pull requests to the main branch

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Use the Node.js version the Next.js app requires

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm run test

      # Run build to ensure the app builds before deployment
      - name: Build the App
        run: npm run build

      # Deploy to Vercel using the CLI
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# project id prj_V5v4FFvu5M4ttaG9VStNJPDOwl8A
# vercel token mTUSyr2qu19CIMedMpDZH9xf
# org id fwu3r6AOqAqCFCBg27hx2aZ6
